name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: k8s-amd64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: mattjmorrison-homelab/actions-helm@152fb694be9a3b41bf6792f032008d42bf4d2a5b
        with:
          chart-path: .
          namespace: argocd
          dry-run: "false"
